import { Store, FoodItem } from '../types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-bf-01',
    name: 'Buddy Foods',
    code: 'BF',
    pin: '1111',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    description: 'Juicy artisan burgers, loaded fries, cheesy wraps & thick milkshakes',
    rating_avg: 4.8,
  },
  {
    id: 'store-hs-02',
    name: 'Hydret Spot',
    code: 'HS',
    pin: '2222',
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=800&q=80',
    description: 'Cold-pressed juices, protein smoothies, boba teas & fresh fruit bowls',
    rating_avg: 4.9,
  },
  {
    id: 'store-rkm-03',
    name: 'RKM',
    code: 'RKM',
    pin: '3333',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    description: 'Authentic Indian specialities, Paneer Kathi rolls, Dum Biryani & Masala Chai',
    rating_avg: 4.7,
  },
  {
    id: 'store-rt-04',
    name: 'Retro',
    code: 'RT',
    pin: '4444',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    description: 'Woodfired sourdough pizzas, creamy pasta bowls, paninis & Italian espresso',
    rating_avg: 4.6,
  },
];

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  // --- Buddy Foods ---
  {
    id: 'bf-item-1',
    store_id: 'store-bf-01',
    name: 'Double Smash Cheeseburger',
    description: 'Two smashed smash beef/veg patties, cheddar, pickles, grilled onions & special sauce',
    price: 180,
    category: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 42,
  },
  {
    id: 'bf-item-2',
    store_id: 'store-bf-01',
    name: 'Crispy Chicken Loaded Fries',
    description: 'Crinkle fries topped with crispy chicken tender bites, jalapeños, melted queso & ranch',
    price: 130,
    category: 'Sides & Fries',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.8,
    rating_count: 38,
  },
  {
    id: 'bf-item-3',
    store_id: 'store-bf-01',
    name: 'Spicy Mexican Fiesta Wrap',
    description: 'Grilled peppers, black beans, avocado crema, corn salsa & chipotle rice in warm tortilla',
    price: 150,
    category: 'Wraps',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.6,
    rating_count: 19,
  },
  {
    id: 'bf-item-4',
    store_id: 'store-bf-01',
    name: 'Oreo Fudge Monster Milkshake',
    description: 'Rich vanilla ice cream blended with double-stuffed Oreos, chocolate drizzle & whipped cream',
    price: 110,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 55,
  },
  {
    id: 'bf-item-5',
    store_id: 'store-bf-01',
    name: 'Truffle Garlic Parmesan Wings',
    description: '6 pieces crisp fried wings tossed in white truffle oil, garlic butter & shredded parm',
    price: 160,
    category: 'Sides & Fries',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80',
    is_sold_out: true,
    rating_avg: 4.7,
    rating_count: 14,
  },

  // --- Hydret Spot ---
  {
    id: 'hs-item-1',
    store_id: 'store-hs-02',
    name: 'Dragonfruit Acai Energy Smoothie',
    description: 'Organic acai, pitaya, banana, almond milk, topped with chia seeds & granola',
    price: 120,
    category: 'Smoothies',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 31,
  },
  {
    id: 'hs-item-2',
    store_id: 'store-hs-02',
    name: 'Brown Sugar Taro Boba Tea',
    description: 'Slow-cooked brown sugar boba, creamy taro milk tea with signature cheese foam topping',
    price: 140,
    category: 'Boba & Tea',
    image: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.8,
    rating_count: 67,
  },
  {
    id: 'hs-item-3',
    store_id: 'store-hs-02',
    name: 'Matcha Green Tea Cold Brew',
    description: 'Ceremonial grade Uji matcha layered over oat milk with subtle agave sweetener',
    price: 110,
    category: 'Coffee & Tea',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.7,
    rating_count: 22,
  },
  {
    id: 'hs-item-4',
    store_id: 'store-hs-02',
    name: 'Tropical Paradise Fruit Bowl',
    description: 'Fresh sliced mango, kiwi, pineapple, berries with passionfruit drizzle & coconut flakes',
    price: 130,
    category: 'Bowls',
    image: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 18,
  },

  // --- RKM ---
  {
    id: 'rkm-item-1',
    store_id: 'store-rkm-03',
    name: 'Hyderabadi Dum Chicken/Veg Biryani',
    description: 'Aromatic basmati rice cooked on dum with special spices, served with Mirchi Salan & Raita',
    price: 220,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 89,
  },
  {
    id: 'rkm-item-2',
    store_id: 'store-rkm-03',
    name: 'Paneer Butter Masala Kathi Roll',
    description: 'Flaky paratha stuffed with marinated cottage cheese, crunchy onions & mint chutney',
    price: 140,
    category: 'Rolls & Snacks',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.8,
    rating_count: 51,
  },
  {
    id: 'rkm-item-3',
    store_id: 'store-rkm-03',
    name: 'Crispy Punjabi Samosa Chat (2pcs)',
    description: 'Crushed potato samosas topped with spicy chickpeas, sweet tamarind & mint yoghurt',
    price: 80,
    category: 'Rolls & Snacks',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.7,
    rating_count: 40,
  },
  {
    id: 'rkm-item-4',
    store_id: 'store-rkm-03',
    name: 'Kulhad Elaichi Masala Chai',
    description: 'Traditional slow-brewed Indian milk tea infused with green cardamom and ginger',
    price: 30,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 110,
  },

  // --- Retro ---
  {
    id: 'rt-item-1',
    store_id: 'store-rt-04',
    name: 'Truffle Mushroom Sourdough Pizza',
    description: 'Wild forest mushrooms, fior di latte mozzarella, truffle oil & fresh thyme',
    price: 260,
    category: 'Pizzas',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.8,
    rating_count: 33,
  },
  {
    id: 'rt-item-2',
    store_id: 'store-rt-04',
    name: 'Creamy Pesto Penne Pasta',
    description: 'Al dente penne in roasted basil pesto cream sauce with cherry tomatoes & pine nuts',
    price: 210,
    category: 'Pastas',
    image: 'https://images.unsplash.com/photo-1621996346565-e3def61632f0?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.7,
    rating_count: 27,
  },
  {
    id: 'rt-item-3',
    store_id: 'store-rt-04',
    name: 'Smoked Mozzarella & Tomato Panini',
    description: 'Toasted focaccia bread with basil pesto, fresh mozzarella, heirloom tomato & balsamic glaze',
    price: 150,
    category: 'Paninis',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.6,
    rating_count: 15,
  },
  {
    id: 'rt-item-4',
    store_id: 'store-rt-04',
    name: 'Double Shot Caramel Cappuccino',
    description: 'Espresso topped with thick steamed milk foam and house-made salted caramel sauce',
    price: 90,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
    is_sold_out: false,
    rating_avg: 4.9,
    rating_count: 45,
  },
];
